use_frameworks!

platform :ios, '9.0'

target 'WeChatQRCodeScanner_Example' do
  pod 'WeChatQRCodeScanner', :path => '../'

  target 'WeChatQRCodeScanner_Tests' do
    inherit! :search_paths

  end
end
